-- ==========================================
-- STUDENT PERFORMANCE ANALYZER
-- ==========================================

-- Division A = 10 students
-- Division B = 10 students
-- Division C = 10 students
-- Division D = 10 students
-- Division E = 10 students
-- Total = 50 students


DROP TABLE IF EXISTS public.students CASCADE;


-- ==========================================
-- CREATE TABLE
-- ==========================================

CREATE TABLE public.students (

    id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    name TEXT NOT NULL,

    roll TEXT NOT NULL UNIQUE,

    division TEXT NOT NULL,

    maths INTEGER NOT NULL,

    science INTEGER NOT NULL,

    english INTEGER NOT NULL

);


-- ==========================================
-- ROW LEVEL SECURITY
-- ==========================================

ALTER TABLE public.students
ENABLE ROW LEVEL SECURITY;


-- ==========================================
-- SELECT POLICY
-- ==========================================

CREATE POLICY "public read students"

ON public.students

FOR SELECT

TO anon

USING (true);


-- ==========================================
-- INSERT POLICY
-- ==========================================

CREATE POLICY "public insert students"

ON public.students

FOR INSERT

TO anon

WITH CHECK (true);


-- ==========================================
-- DELETE POLICY
-- ==========================================

CREATE POLICY "public delete students"

ON public.students

FOR DELETE

TO anon

USING (true);


-- ==========================================
-- UPDATE POLICY
-- IMPORTANT FOR EDIT BUTTON
-- ==========================================

CREATE POLICY "public update students"

ON public.students

FOR UPDATE

TO anon

USING (true)

WITH CHECK (true);


-- ==========================================
-- DIVISION A
-- ==========================================

INSERT INTO public.students
(
    name,
    roll,
    division,
    maths,
    science,
    english
)

VALUES

(
    'Aarav Sharma',
    'A01',
    'A',
    85,
    80,
    91
),

(
    'Diya Patel',
    'A02',
    'A',
    78,
    75,
    83
),

(
    'Riya Sharma',
    'A03',
    'A',
    95,
    90,
    92
),

(
    'Karan Mehta',
    'A04',
    'A',
    70,
    76,
    76
),

(
    'Sneha Desai',
    'A05',
    'A',
    65,
    68,
    73
),

(
    'Rahul Verma',
    'A06',
    'A',
    82,
    79,
    82
),

(
    'Anaya Joshi',
    'A07',
    'A',
    74,
    78,
    78
),

(
    'Harsh Gupta',
    'A08',
    'A',
    88,
    90,
    89
),

(
    'Mohit Patel',
    'A09',
    'A',
    55,
    58,
    57
),

(
    'Kavya Singh',
    'A10',
    'A',
    80,
    83,
    84
);


-- ==========================================
-- DIVISION B
-- ==========================================

INSERT INTO public.students
(
    name,
    roll,
    division,
    maths,
    science,
    english
)

VALUES

(
    'Dev Shah',
    'B01',
    'B',
    82,
    86,
    79
),

(
    'Isha Patel',
    'B02',
    'B',
    91,
    88,
    94
),

(
    'Yash Mehta',
    'B03',
    'B',
    68,
    72,
    70
),

(
    'Mahi Desai',
    'B04',
    'B',
    74,
    77,
    75
),

(
    'Rohan Joshi',
    'B05',
    'B',
    58,
    61,
    63
),

(
    'Krisha Shah',
    'B06',
    'B',
    87,
    85,
    90
),

(
    'Aditya Patel',
    'B07',
    'B',
    76,
    73,
    78
),

(
    'Nisha Gupta',
    'B08',
    'B',
    93,
    91,
    89
),

(
    'Jay Verma',
    'B09',
    'B',
    49,
    53,
    51
),

(
    'Pooja Mehta',
    'B10',
    'B',
    81,
    79,
    84
);


-- ==========================================
-- DIVISION C
-- ==========================================

INSERT INTO public.students
(
    name,
    roll,
    division,
    maths,
    science,
    english
)

VALUES

(
    'Vivaan Patel',
    'C01',
    'C',
    89,
    91,
    87
),

(
    'Myra Shah',
    'C02',
    'C',
    72,
    70,
    76
),

(
    'Arjun Mehta',
    'C03',
    'C',
    95,
    94,
    96
),

(
    'Aanya Desai',
    'C04',
    'C',
    84,
    82,
    80
),

(
    'Dhruv Patel',
    'C05',
    'C',
    61,
    65,
    63
),

(
    'Sara Joshi',
    'C06',
    'C',
    79,
    77,
    82
),

(
    'Krish Shah',
    'C07',
    'C',
    88,
    86,
    90
),

(
    'Avni Mehta',
    'C08',
    'C',
    69,
    73,
    71
),

(
    'Nakul Desai',
    'C09',
    'C',
    54,
    59,
    56
),

(
    'Tara Patel',
    'C10',
    'C',
    83,
    80,
    85
);


-- ==========================================
-- DIVISION D
-- ==========================================

INSERT INTO public.students
(
    name,
    roll,
    division,
    maths,
    science,
    english
)

VALUES

(
    'Manav Shah',
    'D01',
    'D',
    80,
    84,
    81
),

(
    'Kiara Patel',
    'D02',
    'D',
    92,
    95,
    90
),

(
    'Reyansh Mehta',
    'D03',
    'D',
    73,
    75,
    70
),

(
    'Rudra Desai',
    'D04',
    'D',
    67,
    69,
    72
),

(
    'Aditi Shah',
    'D05',
    'D',
    86,
    82,
    88
),

(
    'Veer Patel',
    'D06',
    'D',
    57,
    62,
    60
),

(
    'Pari Mehta',
    'D07',
    'D',
    78,
    80,
    75
),

(
    'Atharv Joshi',
    'D08',
    'D',
    90,
    87,
    93
),

(
    'Navya Desai',
    'D09',
    'D',
    45,
    48,
    50
),

(
    'Kabir Shah',
    'D10',
    'D',
    71,
    74,
    77
);


-- ==========================================
-- DIVISION E
-- ==========================================

INSERT INTO public.students
(
    name,
    roll,
    division,
    maths,
    science,
    english
)

VALUES

(
    'Shaurya Patel',
    'E01',
    'E',
    94,
    91,
    95
),

(
    'Aarohi Shah',
    'E02',
    'E',
    83,
    86,
    82
),

(
    'Vivaan Mehta',
    'E03',
    'E',
    77,
    75,
    79
),

(
    'Ira Desai',
    'E04',
    'E',
    68,
    70,
    67
),

(
    'Rehaan Patel',
    'E05',
    'E',
    59,
    61,
    58
),

(
    'Anvi Shah',
    'E06',
    'E',
    88,
    90,
    86
),

(
    'Devansh Mehta',
    'E07',
    'E',
    74,
    72,
    76
),

(
    'Meera Desai',
    'E08',
    'E',
    91,
    89,
    93
),

(
    'Laksh Patel',
    'E09',
    'E',
    52,
    55,
    51
),

(
    'Siya Shah',
    'E10',
    'E',
    80,
    84,
    82
);


-- ==========================================
-- VERIFY DATA
-- ==========================================

SELECT
    division,
    COUNT(*) AS student_count

FROM public.students

GROUP BY division

ORDER BY division;


SELECT
    COUNT(*) AS total_students

FROM public.students;